"""Async BLE scanning layer.

Spawns the Swift helper's ``ble-scan`` subcommand, reads its JSONL
stdout in the background, and emits :class:`BLEScanUpdate` snapshots
on a fixed cadence. The TUI consumes the snapshots like
:class:`wifiscope.poller.WiFiPoller` consumes Wi-Fi events — different
sources, same async-iterator shape.

The poller is responsible for:

- maintaining a rolling map ``{identifier: BLEDevice}`` of every
  advertisement seen,
- resolving the manufacturer-data company-ID prefix to a vendor name
  via the bundled Bluetooth SIG snapshot,
- expiring entries unseen for more than ``ttl_s`` seconds (default 30,
  reflecting macOS-side ad coalescing — most active devices repeat
  every few seconds),
- folding rotated-UUID duplicates into a single row using a
  fuzzy-merge over (vendor_id, name, recent RSSI window).

Permission failures are surfaced cleanly: the helper exits with code 3
and a JSON ``{"error": "..."}`` line; the poller flips
``permission_state`` to ``"denied"`` and keeps yielding empty
snapshots so the TUI's BLE panel can render its "(BLE permission
required)" placeholder without crashing.

Subprocess crashes (e.g. SIGKILL during a system Bluetooth restart)
are treated similarly: future snapshots are empty; no exception
bubbles up.
"""

from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncIterator, Awaitable, Callable
from dataclasses import dataclass, replace
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


# ---------- public dataclasses ----------

@dataclass(frozen=True, slots=True)
class BLEDevice:
    """One BLE peripheral as currently understood by the poller.

    ``identifier`` is the CoreBluetooth per-host UUID, lower-cased.
    Modern devices rotate this UUID for privacy, so the same physical
    device can appear under multiple identifiers over time. The
    fuzzy merger in :func:`merge_for_display` collapses such cases by
    matching on ``(vendor_id, name)`` plus an RSSI tolerance window;
    when entries fold, ``merged_count`` exceeds 1 and the renderer
    shows a ``(merged N)`` badge.
    """

    identifier: str
    name: str | None
    vendor: str | None
    vendor_id: int | None
    services: tuple[str, ...]
    rssi_dbm: int | None
    is_connectable: bool
    first_seen: datetime
    last_seen: datetime
    ad_count: int
    merged_count: int = 1


@dataclass(frozen=True, slots=True)
class BLEScanUpdate:
    """One pass of currently-visible BLE devices.

    ``permission_state`` summarises the helper's reachability:

    - ``"granted"``  — at least one ad parsed successfully
    - ``"denied"``   — helper reported ``"bluetooth unauthorized"`` or
      exited with code 3
    - ``"unavailable"`` — the helper binary could not be spawned
    - ``"unknown"``  — initial state before the first event
    """

    devices: list[BLEDevice]
    permission_state: str


# ---------- vendor lookup ----------

_VENDORS_PATH = Path(__file__).resolve().parent / "data" / "bluetooth_vendors.json"


def load_vendors(path: Path | None = None) -> dict[int, str]:
    """Load the bundled Bluetooth-SIG company-ID → vendor-name map.

    The file ships in ``src/wifiscope/data/bluetooth_vendors.json`` and
    is regenerated by ``make update-vendors``. ``_meta`` is filtered
    out. A missing or unreadable file yields an empty dict — vendor
    resolution then falls through to ``None`` and the UI shows the
    raw company ID.
    """
    if path is None:
        path = _VENDORS_PATH
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {}
    out: dict[int, str] = {}
    for k, v in data.items():
        if k == "_meta":
            continue
        try:
            out[int(k)] = str(v)
        except (TypeError, ValueError):
            continue
    return out


def lookup_vendor(company_id: int | None, vendors: dict[int, str]) -> str | None:
    """Resolve a Bluetooth SIG company ID to a vendor name, or None."""
    if company_id is None:
        return None
    return vendors.get(company_id)


# ---------- service category inference ----------

# 16-bit Bluetooth SIG GATT service UUIDs the user is likely to recognise.
# Anything not in this map passes through as the raw UUID, which is
# rarely useful but at least visible. The category names route through
# i18n.t() at the call site so the Chinese UI translates them.
_SERVICE_CATEGORY: dict[str, str] = {
    "180D": "Heart Rate",
    "1812": "HID",
    "1124": "HID Keyboard",
    "1108": "Audio",
    "110A": "Audio",
    "110B": "Audio",
    "110C": "Audio",
    "110D": "Audio",
    "110E": "Audio",
    "110F": "Audio",
    "111E": "Audio",
    "FE9F": "Find My",
    "FD5A": "Find My",
}

# Standard Bluetooth SIG base UUID; 16-bit short codes embed at chars 4-7
# of the 32-char form. macOS sometimes reports the long form, sometimes
# the short — normalise so the lookup always sees the 16-bit code.
_BASE_TAIL = "00001000800000805F9B34FB"


def _normalize_uuid(uuid: str) -> str:
    u = uuid.upper().replace("-", "")
    if len(u) == 32 and u.endswith(_BASE_TAIL) and u.startswith("0000"):
        return u[4:8]
    return u


def service_category(uuid: str) -> str:
    """Map a service UUID to a user-readable category, or pass through."""
    short = _normalize_uuid(uuid)
    return _SERVICE_CATEGORY.get(short, short)


# ---------- line parsing ----------

def _build_device(
    obj: dict[str, Any],
    *,
    vendors: dict[int, str],
    prior: BLEDevice | None,
    now: datetime | None = None,
) -> BLEDevice | None:
    """Promote one decoded advertisement object into a BLEDevice.

    ``prior`` carries forward ``first_seen`` and ``ad_count`` when the
    same identifier has been seen before; otherwise the device is new.
    Returns None if the object lacks a usable ``id`` field.
    """
    identifier = obj.get("id")
    if not isinstance(identifier, str):
        return None
    identifier = identifier.lower()

    name = obj.get("name") if isinstance(obj.get("name"), str) else None
    if name is None and prior is not None:
        # macOS sometimes drops the local-name field on subsequent
        # advertisements from the same device. Carry the prior name
        # forward rather than blanking the row mid-session.
        name = prior.name

    rssi_raw = obj.get("rssi_dbm")
    rssi: int | None
    if isinstance(rssi_raw, bool):
        rssi = None
    elif isinstance(rssi_raw, (int, float)):
        rssi = int(rssi_raw)
    else:
        rssi = None

    is_connectable = bool(obj.get("is_connectable", False))

    services_raw = obj.get("service_uuids") or []
    if isinstance(services_raw, list):
        services = tuple(s for s in services_raw if isinstance(s, str))
    else:
        services = ()
    if not services and prior is not None:
        services = prior.services

    vendor_id_raw = obj.get("manufacturer_id")
    vendor_id: int | None
    if isinstance(vendor_id_raw, bool):
        vendor_id = None
    elif isinstance(vendor_id_raw, (int, float)):
        vendor_id = int(vendor_id_raw)
    else:
        vendor_id = None
    vendor = lookup_vendor(vendor_id, vendors)

    if now is None:
        now = datetime.now(timezone.utc)
    first_seen = prior.first_seen if prior is not None else now
    ad_count = prior.ad_count + 1 if prior is not None else 1

    return BLEDevice(
        identifier=identifier,
        name=name,
        vendor=vendor,
        vendor_id=vendor_id,
        services=services,
        rssi_dbm=rssi,
        is_connectable=is_connectable,
        first_seen=first_seen,
        last_seen=now,
        ad_count=ad_count,
    )


def update_from_line(
    devices: dict[str, BLEDevice],
    line: str,
    *,
    vendors: dict[int, str],
    now: datetime | None = None,
) -> str | None:
    """Apply one JSONL line to the device map, in place.

    Returns:
        - ``"permission_denied"`` if the line was a permission error
          from the helper.
        - ``"error"`` if the line was a non-permission error.
        - ``None`` for either a valid advertisement (devices mutated)
          or a malformed line (silently skipped).
    """
    try:
        obj = json.loads(line)
    except (json.JSONDecodeError, ValueError):
        return None
    if not isinstance(obj, dict):
        return None
    if "error" in obj:
        err = str(obj.get("error", "")).lower()
        if "unauthor" in err:
            return "permission_denied"
        return "error"
    identifier = obj.get("id")
    if not isinstance(identifier, str):
        return None
    key = identifier.lower()
    prior = devices.get(key)
    device = _build_device(obj, vendors=vendors, prior=prior, now=now)
    if device is not None:
        devices[key] = device
    return None


# ---------- expiry + fuzzy merge ----------

def expire_devices(
    devices: dict[str, BLEDevice],
    *,
    now: datetime,
    ttl_s: float,
) -> dict[str, BLEDevice]:
    """Return a new map with entries last-seen earlier than ``ttl_s``
    seconds before ``now`` removed.
    """
    return {
        k: v for k, v in devices.items()
        if (now - v.last_seen).total_seconds() <= ttl_s
    }


def merge_for_display(
    devices: list[BLEDevice],
    *,
    rssi_window_db: int = 10,
) -> list[BLEDevice]:
    """Fold rotated-UUID duplicates per the spec's fuzzy-merge rule.

    Two records with the same ``(vendor_id, name)`` whose RSSIs sit
    within ``±rssi_window_db`` of one another are merged into a single
    representative device. ``ad_count`` is summed; ``merged_count``
    records how many entries collapsed.

    Devices with both ``vendor_id`` and ``name`` blank are never
    merged — the heuristic is too risky on anonymous advertisers (the
    spec calls this out under "lightweight, transparent").
    """
    out: list[BLEDevice] = []
    bucket_groups: dict[tuple[int | None, str | None], list[BLEDevice]] = {}
    unmergeable: list[BLEDevice] = []
    for d in devices:
        if d.vendor_id is None and d.name is None:
            unmergeable.append(d)
            continue
        bucket_groups.setdefault((d.vendor_id, d.name), []).append(d)

    for group in bucket_groups.values():
        remaining = sorted(
            group,
            key=lambda d: d.rssi_dbm if d.rssi_dbm is not None else -200,
            reverse=True,
        )
        while remaining:
            anchor = remaining[0]
            anchor_rssi = anchor.rssi_dbm if anchor.rssi_dbm is not None else -200
            cluster = [anchor]
            kept: list[BLEDevice] = []
            for d in remaining[1:]:
                rssi = d.rssi_dbm if d.rssi_dbm is not None else -200
                if abs(rssi - anchor_rssi) <= rssi_window_db:
                    cluster.append(d)
                else:
                    kept.append(d)
            out.append(_fold_cluster(cluster) if len(cluster) > 1 else anchor)
            remaining = kept

    out.extend(unmergeable)
    out.sort(
        key=lambda d: d.rssi_dbm if d.rssi_dbm is not None else -200,
        reverse=True,
    )
    return out


def _fold_cluster(cluster: list[BLEDevice]) -> BLEDevice:
    """Combine cluster members into one merged BLEDevice.

    The strongest-RSSI entry serves as the representative; service
    UUIDs are unioned in first-seen order, ad_count is summed, and
    first/last seen span the union. Identifier is taken from the
    strongest entry — the rest are by definition rotated views of
    "the same thing", so any of them is as good as another.
    """
    primary = max(
        cluster,
        key=lambda d: d.rssi_dbm if d.rssi_dbm is not None else -200,
    )
    seen: set[str] = set()
    services: list[str] = []
    for d in cluster:
        for s in d.services:
            if s not in seen:
                seen.add(s)
                services.append(s)
    return replace(
        primary,
        services=tuple(services),
        ad_count=sum(d.ad_count for d in cluster),
        merged_count=len(cluster),
        first_seen=min(d.first_seen for d in cluster),
        last_seen=max(d.last_seen for d in cluster),
    )


# ---------- poller ----------

class BLEPoller:
    """Background driver around ``wifiscope-helper ble-scan``.

    Single-use: call :meth:`events` once and iterate the resulting
    async generator. On generator close (consumer breaks out, or the
    surrounding asyncio task is cancelled) the helper subprocess is
    terminated and the internal tasks are awaited.

    The optional ``_spawn`` constructor argument is a test seam: when
    set, it replaces the production ``asyncio.create_subprocess_exec``
    call with a callable that returns a process-shaped object whose
    ``stdout`` is an async-iterable of bytes lines and whose ``wait``
    coroutine resolves to a return code.
    """

    def __init__(
        self,
        helper_path: str,
        *,
        ttl_s: float = 30.0,
        snapshot_interval_s: float = 1.0,
        vendors: dict[int, str] | None = None,
        _spawn: Callable[[], Awaitable[Any]] | None = None,
    ) -> None:
        self._helper_path = helper_path
        self._ttl_s = ttl_s
        self._snapshot_interval_s = snapshot_interval_s
        self._vendors = vendors if vendors is not None else load_vendors()
        self._devices: dict[str, BLEDevice] = {}
        self._queue: asyncio.Queue[BLEScanUpdate] = asyncio.Queue()
        self._proc: Any = None
        self._proc_ended = False
        self._permission_state: str = "unknown"
        self._tasks: list[asyncio.Task[Any]] = []
        self._stopped = False
        self._spawn_override = _spawn

    async def events(self) -> AsyncIterator[BLEScanUpdate]:
        loop = asyncio.get_running_loop()
        self._tasks = [
            loop.create_task(self._reader_loop(), name="ble-reader"),
            loop.create_task(self._snapshot_loop(), name="ble-snapshot"),
        ]
        try:
            while True:
                yield await self._queue.get()
        finally:
            self.stop()
            await asyncio.gather(*self._tasks, return_exceptions=True)

    def stop(self) -> None:
        self._stopped = True
        for t in self._tasks:
            t.cancel()
        proc = self._proc
        if proc is not None and getattr(proc, "returncode", None) is None:
            try:
                proc.terminate()
            except (ProcessLookupError, OSError):
                pass

    async def _reader_loop(self) -> None:
        try:
            if self._spawn_override is not None:
                self._proc = await self._spawn_override()
            else:
                self._proc = await asyncio.create_subprocess_exec(
                    self._helper_path, "ble-scan",
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.DEVNULL,
                )
        except (OSError, FileNotFoundError):
            self._permission_state = "unavailable"
            self._proc_ended = True
            return

        stdout = getattr(self._proc, "stdout", None)
        if stdout is None:
            self._proc_ended = True
            return

        try:
            async for raw in stdout:
                if self._stopped:
                    break
                line = raw.decode("utf-8", errors="replace").rstrip()
                if not line:
                    continue
                state = update_from_line(
                    self._devices, line, vendors=self._vendors,
                )
                if state == "permission_denied":
                    self._permission_state = "denied"
                elif state == "error" and self._permission_state == "unknown":
                    self._permission_state = "error"
                elif state is None and self._permission_state in ("unknown", "error"):
                    # A successful parse implies we are getting real
                    # advertisements — flip to granted exactly once.
                    if any(self._devices):
                        self._permission_state = "granted"
        except (asyncio.CancelledError, GeneratorExit):
            raise
        except Exception:
            # Any unexpected stream error: stop reading. The snapshot
            # loop continues yielding empty snapshots (per spec) until
            # the consumer breaks.
            pass

        try:
            rc = await self._proc.wait()
        except (asyncio.CancelledError, GeneratorExit):
            raise
        except Exception:
            rc = None
        if rc == 3:
            self._permission_state = "denied"
        self._proc_ended = True

    async def _snapshot_loop(self) -> None:
        # Always emit at least one snapshot promptly so consumers see
        # the initial "(scanning…)" state without waiting a full
        # interval.
        try:
            while not self._stopped:
                now = datetime.now(timezone.utc)
                self._devices = expire_devices(
                    self._devices, now=now, ttl_s=self._ttl_s,
                )
                merged = merge_for_display(list(self._devices.values()))
                await self._queue.put(BLEScanUpdate(
                    devices=merged,
                    permission_state=self._permission_state,
                ))
                await asyncio.sleep(self._snapshot_interval_s)
        except asyncio.CancelledError:
            raise
