"""Async BLE scanning layer.

Spawns the Swift helper's ``ble-scan`` subcommand, reads its JSONL
stdout in the background, and emits :class:`BLEScanUpdate` snapshots
on a fixed cadence. The TUI consumes the snapshots like
:class:`wifiscope.poller.WiFiPoller` consumes Wi-Fi events — different
sources, same async-iterator shape.

The poller is responsible for:

- maintaining a rolling map ``{identifier: BLEDevice}`` of every
  advertisement seen,
- resolving the manufacturer-data company-ID prefix to a vendor name
  via the bundled Bluetooth SIG snapshot,
- expiring entries unseen for more than ``ttl_s`` seconds (default 30,
  reflecting macOS-side ad coalescing — most active devices repeat
  every few seconds),
- folding rotated-UUID duplicates into a single row using a
  fuzzy-merge over (vendor_id, name, recent RSSI window).

Permission failures are surfaced cleanly: the helper exits with code 3
and a JSON ``{"error": "..."}`` line; the poller flips
``permission_state`` to ``"denied"`` and keeps yielding empty
snapshots so the TUI's BLE panel can render its "(BLE permission
required)" placeholder without crashing.

Subprocess crashes (e.g. SIGKILL during a system Bluetooth restart)
are treated similarly: future snapshots are empty; no exception
bubbles up.
"""

from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncIterator, Awaitable, Callable
from dataclasses import dataclass, field, replace
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


# ---------- public dataclasses ----------

@dataclass(frozen=True, slots=True)
class BLEDevice:
    """One BLE peripheral as currently understood by the poller.

    ``identifier`` is the CoreBluetooth per-host UUID, lower-cased.
    Modern devices rotate this UUID for privacy, so the same physical
    device can appear under multiple identifiers over time. The
    fuzzy merger in :func:`merge_for_display` collapses such cases by
    matching on ``(vendor_id, name)`` plus an RSSI tolerance window;
    when entries fold, ``merged_count`` exceeds 1 and the renderer
    shows a ``(merged N)`` badge.

    Schema-3 (v0.6.0+) optional fields:

    - ``type`` is the helper's public-format detection result —
      ``"iBeacon"``, ``"AirTag"``, ``"Eddystone-URL"``, ``"Tile"``,
      ``"SmartTag"``, ``"Swift Pair"``, etc. None when the device's
      advertisement is not in any well-documented format.
    - ``device_class`` is the Apple Nearby Info device-class nibble
      decoded into ``"iPhone"`` / ``"iPad"`` / ``"Mac"`` / ``"Apple
      TV"`` / ``"HomePod"`` / ``"Apple Watch"``. None for non-Apple
      devices and for Apple devices not advertising Nearby Info.
    - ``is_connected`` is True for entries that came from the helper's
      ``retrieveConnectedPeripherals`` snapshot (your AirPods, Magic
      Keyboard, etc., which are not advertising and so otherwise
      invisible to the BLE panel). Connected entries have no RSSI
      reading and are sorted alphabetically by name in the panel.
    """

    identifier: str
    name: str | None
    vendor: str | None
    vendor_id: int | None
    services: tuple[str, ...]
    rssi_dbm: int | None
    is_connectable: bool
    first_seen: datetime
    last_seen: datetime
    ad_count: int
    merged_count: int = 1
    type: str | None = None
    device_class: str | None = None
    is_connected: bool = False


@dataclass(frozen=True, slots=True)
class BLEScanUpdate:
    """One pass of currently-visible BLE devices.

    ``permission_state`` summarises the helper's reachability:

    - ``"granted"``  — at least one ad parsed successfully
    - ``"denied"``   — helper reported ``"bluetooth unauthorized"`` or
      exited with code 3
    - ``"unavailable"`` — the helper binary could not be spawned
    - ``"unknown"``  — initial state before the first event

    ``devices`` is the advertising list, post-merge, sorted by RSSI
    desc. ``connected`` is a parallel list of currently-connected
    peripherals (AirPods you're listening to, Magic Keyboard you're
    typing on) that the OS knows about but that are not advertising.
    Connected entries skip the fuzzy-merger (no RSSI, no UUID rotation).
    """

    devices: list[BLEDevice]
    permission_state: str
    connected: list[BLEDevice] = field(default_factory=list)


# ---------- vendor lookup ----------

_VENDORS_PATH = Path(__file__).resolve().parent / "data" / "bluetooth_vendors.json"


def load_vendors(path: Path | None = None) -> dict[int, str]:
    """Load the bundled Bluetooth-SIG company-ID → vendor-name map.

    The file ships in ``src/wifiscope/data/bluetooth_vendors.json`` and
    is regenerated by ``make update-vendors``. ``_meta`` is filtered
    out. A missing or unreadable file yields an empty dict — vendor
    resolution then falls through to ``None`` and the UI shows the
    raw company ID.
    """
    if path is None:
        path = _VENDORS_PATH
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {}
    out: dict[int, str] = {}
    for k, v in data.items():
        if k == "_meta":
            continue
        try:
            out[int(k)] = str(v)
        except (TypeError, ValueError):
            continue
    return out


def lookup_vendor(company_id: int | None, vendors: dict[int, str]) -> str | None:
    """Resolve a Bluetooth SIG company ID to a vendor name, or None."""
    if company_id is None:
        return None
    return vendors.get(company_id)


# ---------- IEEE OUI lookup (for connected peripherals) ----------
#
# Connected peripherals come from IOBluetoothDevice (system BT stack) and
# do not carry the manufacturer_data field that the advertising path
# uses for vendor resolution — we only have the device's BT MAC. Match
# the first 3 octets against a curated subset of the IEEE OUI registry
# instead. The bundled JSON covers Apple comprehensively (a Mac is most
# likely to have Apple peripherals connected) plus the major consumer
# Bluetooth vendors; anything else stays unknown.

_OUIS_PATH = Path(__file__).resolve().parent / "data" / "bluetooth_ouis.json"


def load_ouis(path: Path | None = None) -> dict[str, str]:
    """Load the bundled IEEE OUI prefix → vendor-name map.

    Keys are normalised to ``aa:bb:cc`` (lower-case, colon-separated 3
    octets). ``_meta`` is filtered out. A missing / unreadable file
    yields an empty dict; vendor lookup then falls through to None.
    """
    if path is None:
        path = _OUIS_PATH
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {}
    return {
        str(k).lower(): str(v)
        for k, v in data.items()
        if k != "_meta" and isinstance(v, str)
    }


def lookup_oui_vendor(
    identifier: str | None, ouis: dict[str, str]
) -> str | None:
    """Resolve a BT MAC (any common separator: ``:``, ``-``, none) to
    a vendor name via its first 3 octets, or None when unknown.
    Tolerant of the ``38-09-fb-0b-be-60`` form the helper emits.
    """
    if not identifier:
        return None
    cleaned = identifier.replace("-", "").replace(":", "").lower()
    if len(cleaned) < 6 or any(c not in "0123456789abcdef" for c in cleaned):
        return None
    prefix = f"{cleaned[0:2]}:{cleaned[2:4]}:{cleaned[4:6]}"
    return ouis.get(prefix)


# ---------- service category inference ----------

# 16-bit Bluetooth SIG GATT service UUIDs the user is likely to recognise.
# These hand-curated names take priority over the upstream SIG names —
# the SIG label for 0x1812 is "Human Interface Device" but every keyboard
# user we have ever met calls it "HID". Anything missed here falls
# through to the bundled SIG GATT-services map, then to the bundled
# member-UUID map, then to the raw UUID. The names route through
# i18n.t() at the call site so the Chinese UI translates them.
_SERVICE_CATEGORY: dict[str, str] = {
    "180D": "Heart Rate",
    "1812": "HID",
    "1124": "HID Keyboard",
    "1108": "Audio",
    "110A": "Audio",
    "110B": "Audio",
    "110C": "Audio",
    "110D": "Audio",
    "110E": "Audio",
    "110F": "Audio",
    "111E": "Audio",
    "FE9F": "Find My",
    "FD5A": "Find My",
}

# Standard Bluetooth SIG base UUID; 16-bit short codes embed at chars 4-7
# of the 32-char form. macOS sometimes reports the long form, sometimes
# the short — normalise so the lookup always sees the 16-bit code.
_BASE_TAIL = "00001000800000805F9B34FB"


def _normalize_uuid(uuid: str) -> str:
    u = uuid.upper().replace("-", "")
    if len(u) == 32 and u.endswith(_BASE_TAIL) and u.startswith("0000"):
        return u[4:8]
    return u


# ---------- bundled SIG UUID tables (GATT services + member UUIDs) ----------

_GATT_SERVICES_PATH = (
    Path(__file__).resolve().parent / "data" / "bluetooth_gatt_services.json"
)
_MEMBER_UUIDS_PATH = (
    Path(__file__).resolve().parent / "data" / "bluetooth_member_uuids.json"
)


def _load_uuid_table(path: Path) -> dict[str, str]:
    """Load a 4-char hex-keyed JSON table; ``_meta`` filtered out."""
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {}
    return {
        str(k).upper(): str(v)
        for k, v in data.items()
        if k != "_meta" and isinstance(v, str)
    }


def load_gatt_services(path: Path | None = None) -> dict[str, str]:
    """Load the bundled SIG 16-bit GATT service UUID → name map.

    Source: ``assigned_numbers/uuids/service_uuids.yaml``. Regenerate
    with ``make update-vendors``. A missing file is tolerated and
    yields an empty dict; UUIDs then fall through to the raw value.
    """
    return _load_uuid_table(path or _GATT_SERVICES_PATH)


def load_member_uuids(path: Path | None = None) -> dict[str, str]:
    """Load the bundled SIG 16-bit member-assigned UUID → company map.

    Source: ``assigned_numbers/uuids/member_uuids.yaml``. Each entry
    is a UUID the SIG handed out to one company (e.g. FDAA → Xiaomi).
    Used both for the service column ("Xiaomi service") and as a
    vendor fallback when the device's advertisement omits the
    manufacturer-data company-ID.
    """
    return _load_uuid_table(path or _MEMBER_UUIDS_PATH)


def lookup_member_vendor(
    services: tuple[str, ...] | list[str],
    member_uuids: dict[str, str],
) -> str | None:
    """Resolve a vendor name from the first member UUID in ``services``.

    Used as a fallback when ``manufacturer_id`` is absent. Returns the
    SIG-listed company name verbatim ("Xiaomi Inc.", "Sony Mobile
    Communications") so it sits next to manufacturer-derived vendors
    in the UI without flicker.
    """
    if not member_uuids:
        return None
    for s in services:
        if not isinstance(s, str):
            continue
        short = _normalize_uuid(s)
        name = member_uuids.get(short)
        if name:
            return name
    return None


def service_category(
    uuid: str,
    *,
    gatt: dict[str, str] | None = None,
    member: dict[str, str] | None = None,
) -> str:
    """Map a service UUID to a user-readable category, or pass through.

    Resolution order:
      1. Hand-curated ``_SERVICE_CATEGORY`` (project-specific friendly
         names like "HID" instead of "Human Interface Device").
      2. ``gatt`` (full SIG 16-bit GATT services list — Battery,
         Device Information, Environmental Sensing, etc.).
      3. ``member`` (SIG-assigned member UUIDs — FDAA → Xiaomi,
         FD2A → Sony Corporation, etc.).
      4. Raw UUID as last resort.

    ``gatt`` and ``member`` default to the bundled tables when
    omitted; tests can pass empty dicts to verify the hand-curated
    layer in isolation.
    """
    short = _normalize_uuid(uuid)
    hit = _SERVICE_CATEGORY.get(short)
    if hit is not None:
        return hit
    if gatt is None:
        gatt = load_gatt_services()
    hit = gatt.get(short)
    if hit is not None:
        return hit
    if member is None:
        member = load_member_uuids()
    hit = member.get(short)
    if hit is not None:
        return hit
    return short


# ---------- public-format detection ----------

# Bluetooth SIG company IDs we branch on for deep identification.
_COMPANY_APPLE = 0x004C
_COMPANY_MICROSOFT = 0x0006
_COMPANY_SAMSUNG = 0x0075


def _normalize_service_uuids(obj: dict[str, Any]) -> set[str]:
    raw = obj.get("service_uuids") or []
    if not isinstance(raw, list):
        return set()
    out: set[str] = set()
    for s in raw:
        if isinstance(s, str):
            out.add(_normalize_uuid(s))
    return out


def _apple_nearby_info_device_class(action_byte: int) -> str | None:
    """Map the high nibble of the Apple Nearby Info action byte to a
    device class name. Lower-nibble bits are activity / status flags
    we ignore. Mapping comes from the public ``furiousMAC/continuity``
    reference; per-model precision is impossible from this byte alone.
    """
    nibble = (action_byte >> 4) & 0x0F
    return {
        0x1: "iPhone",
        0x2: "iPad",
        0x4: "Mac",
        0x6: "Apple TV",
        0x7: "HomePod",
        0x9: "Apple Watch",
    }.get(nibble)


# Apple Continuity protocol type-byte → human-readable label, sourced
# from the public ``furiousMAC/continuity`` reverse-engineering. We
# only label types whose meaning is stable across iOS versions; the
# encrypted payload tail is ignored. Resolves the bulk of the
# "Apple, Inc. (unknown)" rows users see in the BLE panel — Apple
# devices broadcast Continuity packets without ever populating the
# advertisement's local-name field, so without this map the row has
# no name to show.
_APPLE_CONTINUITY_TYPE: dict[int, str] = {
    0x05: "AirDrop",
    0x07: "AirPods",
    0x09: "AirPlay target",
    0x0A: "AirPlay source",
    0x0B: "Watch pairing",
    0x0C: "Handoff",
    0x0D: "Tethering target",
    0x0E: "Tethering source",
    0x0F: "Nearby Action",
}


def detect_advertisement(obj: dict[str, Any]) -> tuple[str | None, str | None]:
    """Classify an advertisement payload into (type, device_class).

    Mirrors ``helper/Sources/wifiscope-helper/main.swift:BLEAdParser.detect``.
    Used by :func:`update_from_line` as a fallback when the helper does
    not emit ``type`` / ``device_class`` (older schema-2 bundles), and
    as the deterministic, hermetic algorithm surface that the Python
    test suite exercises directly without needing a Swift toolchain.

    The detector is deliberately conservative — it only labels devices
    whose formats are publicly documented (Tier 1 in the spec). Anything
    outside those returns ``(None, None)``; the panel falls back to
    vendor + service-category for those rows.
    """
    services = _normalize_service_uuids(obj)
    company_id = obj.get("manufacturer_id")
    if isinstance(company_id, bool) or not isinstance(company_id, int):
        company_id = None

    mfg_hex = obj.get("manufacturer_hex")
    mfg_bytes: bytes | None = None
    if isinstance(mfg_hex, str):
        try:
            mfg_bytes = bytes.fromhex(mfg_hex)
        except ValueError:
            mfg_bytes = None

    # 1. Manufacturer-data branches first — disambiguates FD5A (Apple
    #    Find My vs Samsung SmartTag) before service-UUID rules fire.
    if mfg_bytes is not None and company_id is not None:
        if company_id == _COMPANY_APPLE and len(mfg_bytes) >= 3:
            type_byte = mfg_bytes[2]
            if type_byte == 0x02:
                return "iBeacon", None
            if type_byte == 0x10:
                dc = None
                if len(mfg_bytes) >= 6:
                    dc = _apple_nearby_info_device_class(mfg_bytes[5])
                return None, dc
            if type_byte == 0x12:
                # Owner-paired AirTag payloads are ~25 bytes; lost-mode
                # Find My broadcasts are shorter. Use the length as a
                # cheap discriminator — false negatives just degrade to
                # "Find My target", which is still actionable.
                is_airtag = len(mfg_bytes) >= 25
                return ("AirTag" if is_airtag else "Find My target"), None
            label = _APPLE_CONTINUITY_TYPE.get(type_byte)
            if label is not None:
                return label, None
        if company_id == _COMPANY_MICROSOFT and len(mfg_bytes) >= 3:
            if mfg_bytes[2] == 0x03:
                return "Swift Pair", None
        if company_id == _COMPANY_SAMSUNG and "FD5A" in services:
            return "SmartTag", None

    # 2. Service-UUID-based detections (after manufacturer rules so a
    #    Samsung SmartTag advertising FD5A is labelled correctly).
    if "FEAA" in services:
        return "Eddystone", None
    if "FEED" in services or "FEEC" in services:
        return "Tile", None
    if "FD5A" in services:
        return "Find My target", None

    return None, None


# ---------- line parsing ----------

def _build_device(
    obj: dict[str, Any],
    *,
    vendors: dict[int, str],
    prior: BLEDevice | None,
    now: datetime | None = None,
    member_uuids: dict[str, str] | None = None,
) -> BLEDevice | None:
    """Promote one decoded advertisement object into a BLEDevice.

    ``prior`` carries forward ``first_seen`` and ``ad_count`` when the
    same identifier has been seen before; otherwise the device is new.
    Returns None if the object lacks a usable ``id`` field.
    """
    identifier = obj.get("id")
    if not isinstance(identifier, str):
        return None
    identifier = identifier.lower()

    name = obj.get("name") if isinstance(obj.get("name"), str) else None
    if name is None and prior is not None:
        # macOS sometimes drops the local-name field on subsequent
        # advertisements from the same device. Carry the prior name
        # forward rather than blanking the row mid-session.
        name = prior.name

    rssi_raw = obj.get("rssi_dbm")
    rssi: int | None
    if isinstance(rssi_raw, bool):
        rssi = None
    elif isinstance(rssi_raw, (int, float)):
        rssi = int(rssi_raw)
    else:
        rssi = None
    # CoreBluetooth's documented "RSSI unavailable" sentinel is 127, and
    # any non-negative value is implausible for received signal strength.
    # The new helper filters this out at the source, but we keep a
    # defensive check here so older helper bundles or unusual data paths
    # cannot leak the sentinel through and corrupt RSSI-sorted lists or
    # the diagnostic-panel Closest line.
    if rssi is not None and (rssi >= 0 or rssi < -200):
        rssi = None

    is_connectable = bool(obj.get("is_connectable", False))

    services_raw = obj.get("service_uuids") or []
    if isinstance(services_raw, list):
        services = tuple(s for s in services_raw if isinstance(s, str))
    else:
        services = ()
    if not services and prior is not None:
        services = prior.services

    vendor_id_raw = obj.get("manufacturer_id")
    vendor_id: int | None
    if isinstance(vendor_id_raw, bool):
        vendor_id = None
    elif isinstance(vendor_id_raw, (int, float)):
        vendor_id = int(vendor_id_raw)
    else:
        vendor_id = None
    # macOS / CoreBluetooth interleaves primary advertisements (which
    # carry manufacturer-specific data) with scan-response packets that
    # commonly omit it. Without this carry-forward the vendor_id flickers
    # between e.g. 76 (Apple) and None across consecutive callbacks for
    # the same device, which makes the vendor column flap and — more
    # importantly — fragments merge_for_display's (vendor_id, name)
    # bucketing across UUID rotations, breaking the (merged N) feature
    # in the exact case it is meant to address.
    if vendor_id is None and prior is not None:
        vendor_id = prior.vendor_id
    vendor = lookup_vendor(vendor_id, vendors)
    # Fallback: if the advertisement has no manufacturer ID but does
    # carry a SIG-assigned member UUID, use the company that owns
    # that UUID. Resolves rows that would otherwise show "(unknown)"
    # for known vendors like SIANA Systems / Audiodo / etc.
    if vendor is None and services:
        if member_uuids is None:
            member_uuids = load_member_uuids()
        vendor = lookup_member_vendor(services, member_uuids)
    if vendor is None and prior is not None:
        # Same flicker-protection as vendor_id: a scan-response packet
        # without manufacturer data should not blank out a name we
        # already established for this device on a prior advertisement.
        vendor = prior.vendor

    if now is None:
        now = datetime.now(timezone.utc)
    first_seen = prior.first_seen if prior is not None else now
    ad_count = prior.ad_count + 1 if prior is not None else 1

    # Schema-3 fields (helper-supplied) win over Python-side detection;
    # the latter exists for back-compat with schema-2 bundles and as a
    # testable mirror of the Swift parser. Carry forward from prior so
    # that a scan-response line that omits these fields does not blank
    # out a label we already established.
    raw_type = obj.get("type")
    raw_dc = obj.get("device_class")
    detect_type: str | None = raw_type if isinstance(raw_type, str) else None
    detect_dc: str | None = raw_dc if isinstance(raw_dc, str) else None
    if detect_type is None and detect_dc is None:
        detect_type, detect_dc = detect_advertisement(obj)
    if detect_type is None and prior is not None:
        detect_type = prior.type
    if detect_dc is None and prior is not None:
        detect_dc = prior.device_class

    return BLEDevice(
        identifier=identifier,
        name=name,
        vendor=vendor,
        vendor_id=vendor_id,
        services=services,
        rssi_dbm=rssi,
        is_connectable=is_connectable,
        first_seen=first_seen,
        last_seen=now,
        ad_count=ad_count,
        type=detect_type,
        device_class=detect_dc,
    )


def _build_connected_device(
    obj: dict[str, Any],
    *,
    prior: BLEDevice | None,
    ouis: dict[str, str] | None = None,
    now: datetime | None = None,
) -> BLEDevice | None:
    """Promote a `{"connected": true, ...}` line into a BLEDevice.

    The advertisement-side ``manufacturer_id`` is unavailable here (the
    helper sources connected rows from IOBluetoothDevice, not from a
    BLE scan), so ``vendor_id`` always stays None. Vendor itself is
    looked up from the BT MAC's OUI prefix when we can — that's the
    only public-data path we have, and it cleanly identifies Apple's
    own peripherals (Magic Keyboard / Trackpad / Mouse / AirPods) plus
    the major third-party headphone / accessory vendors. ``type`` /
    ``device_class`` stay blank — those come from advertisement byte
    parsing which is not run on connected entries.
    """
    identifier = obj.get("id")
    if not isinstance(identifier, str):
        return None
    identifier = identifier.lower()

    name = obj.get("name") if isinstance(obj.get("name"), str) else None
    if name is None and prior is not None:
        name = prior.name

    services_raw = obj.get("service_uuids") or []
    if isinstance(services_raw, list):
        services = tuple(s for s in services_raw if isinstance(s, str))
    else:
        services = ()
    if not services and prior is not None:
        services = prior.services

    vendor: str | None = None
    if ouis:
        vendor = lookup_oui_vendor(identifier, ouis)
    if vendor is None and prior is not None:
        vendor = prior.vendor

    if now is None:
        now = datetime.now(timezone.utc)
    first_seen = prior.first_seen if prior is not None else now

    return BLEDevice(
        identifier=identifier,
        name=name,
        vendor=vendor,
        vendor_id=None,
        services=services,
        rssi_dbm=None,
        is_connectable=True,
        first_seen=first_seen,
        last_seen=now,
        ad_count=0,
        is_connected=True,
    )


def update_from_line(
    devices: dict[str, BLEDevice],
    line: str,
    *,
    vendors: dict[int, str],
    now: datetime | None = None,
    connected: dict[str, BLEDevice] | None = None,
    ouis: dict[str, str] | None = None,
    member_uuids: dict[str, str] | None = None,
) -> str | None:
    """Apply one JSONL line to the device map, in place.

    The optional ``connected`` dict, when supplied, is a parallel store
    for ``retrieveConnectedPeripherals`` snapshots. Connected entries
    skip ``devices`` entirely — they have no RSSI, no UUID rotation, no
    fuzzy-merge involvement, and a different lifecycle (pruned by the
    helper's ``connected_snapshot`` sentinel rather than by TTL). When
    ``connected`` is None, ``connected:true`` and ``connected_snapshot``
    lines are silently dropped — preserves the schema-2 caller surface.

    Returns:
        - ``"permission_denied"`` if the line was a permission error
          from the helper.
        - ``"error"`` if the line was a non-permission error.
        - ``None`` for any other case (valid advertisement, valid
          connected line, valid snapshot sentinel, or malformed line).
    """
    try:
        obj = json.loads(line)
    except (json.JSONDecodeError, ValueError):
        return None
    if not isinstance(obj, dict):
        return None
    if "error" in obj:
        err = str(obj.get("error", "")).lower()
        if "unauthor" in err:
            return "permission_denied"
        return "error"

    # Connected-snapshot sentinel: the helper just finished one round
    # of retrieveConnectedPeripherals; prune entries whose IDs are not
    # in the supplied id list. An empty list means "no connected
    # peripherals right now" — clear the dict entirely.
    if obj.get("connected_snapshot") is True:
        if connected is None:
            return None
        ids_raw = obj.get("ids") or []
        if not isinstance(ids_raw, list):
            return None
        keep = {str(i).lower() for i in ids_raw if isinstance(i, str)}
        for key in list(connected.keys()):
            if key not in keep:
                del connected[key]
        return None

    # Connected-peripheral row: route to the parallel dict and never
    # the advertising one.
    if obj.get("connected") is True:
        if connected is None:
            return None
        identifier = obj.get("id")
        if not isinstance(identifier, str):
            return None
        key = identifier.lower()
        prior = connected.get(key)
        device = _build_connected_device(obj, prior=prior, ouis=ouis, now=now)
        if device is not None:
            connected[key] = device
        return None

    identifier = obj.get("id")
    if not isinstance(identifier, str):
        return None
    key = identifier.lower()
    prior = devices.get(key)
    device = _build_device(
        obj, vendors=vendors, prior=prior, now=now,
        member_uuids=member_uuids,
    )
    if device is not None:
        devices[key] = device
    return None


# ---------- expiry + fuzzy merge ----------

def expire_devices(
    devices: dict[str, BLEDevice],
    *,
    now: datetime,
    ttl_s: float,
) -> dict[str, BLEDevice]:
    """Return a new map with entries last-seen earlier than ``ttl_s``
    seconds before ``now`` removed.
    """
    return {
        k: v for k, v in devices.items()
        if (now - v.last_seen).total_seconds() <= ttl_s
    }


def merge_for_display(
    devices: list[BLEDevice],
    *,
    rssi_window_db: int = 10,
) -> list[BLEDevice]:
    """Fold rotated-UUID duplicates per the spec's fuzzy-merge rule.

    Two records with the same ``(vendor_id, name)`` whose RSSIs sit
    within ``±rssi_window_db`` of one another are merged into a single
    representative device. ``ad_count`` is summed; ``merged_count``
    records how many entries collapsed.

    Devices with both ``vendor_id`` and ``name`` blank are never
    merged — the heuristic is too risky on anonymous advertisers (the
    spec calls this out under "lightweight, transparent").
    """
    out: list[BLEDevice] = []
    bucket_groups: dict[tuple[int | None, str | None], list[BLEDevice]] = {}
    unmergeable: list[BLEDevice] = []
    for d in devices:
        if d.vendor_id is None and d.name is None:
            unmergeable.append(d)
            continue
        bucket_groups.setdefault((d.vendor_id, d.name), []).append(d)

    for group in bucket_groups.values():
        remaining = sorted(
            group,
            key=lambda d: d.rssi_dbm if d.rssi_dbm is not None else -200,
            reverse=True,
        )
        while remaining:
            anchor = remaining[0]
            anchor_rssi = anchor.rssi_dbm if anchor.rssi_dbm is not None else -200
            cluster = [anchor]
            kept: list[BLEDevice] = []
            for d in remaining[1:]:
                rssi = d.rssi_dbm if d.rssi_dbm is not None else -200
                if abs(rssi - anchor_rssi) <= rssi_window_db:
                    cluster.append(d)
                else:
                    kept.append(d)
            out.append(_fold_cluster(cluster) if len(cluster) > 1 else anchor)
            remaining = kept

    out.extend(unmergeable)
    out.sort(
        key=lambda d: d.rssi_dbm if d.rssi_dbm is not None else -200,
        reverse=True,
    )
    return out


def _fold_cluster(cluster: list[BLEDevice]) -> BLEDevice:
    """Combine cluster members into one merged BLEDevice.

    The strongest-RSSI entry serves as the representative; service
    UUIDs are unioned in first-seen order, ad_count is summed, and
    first/last seen span the union. Identifier is taken from the
    strongest entry — the rest are by definition rotated views of
    "the same thing", so any of them is as good as another.
    """
    primary = max(
        cluster,
        key=lambda d: d.rssi_dbm if d.rssi_dbm is not None else -200,
    )
    seen: set[str] = set()
    services: list[str] = []
    for d in cluster:
        for s in d.services:
            if s not in seen:
                seen.add(s)
                services.append(s)
    return replace(
        primary,
        services=tuple(services),
        ad_count=sum(d.ad_count for d in cluster),
        merged_count=len(cluster),
        first_seen=min(d.first_seen for d in cluster),
        last_seen=max(d.last_seen for d in cluster),
    )


# ---------- poller ----------

class BLEPoller:
    """Background driver around ``wifiscope-helper ble-scan``.

    Single-use: call :meth:`events` once and iterate the resulting
    async generator. On generator close (consumer breaks out, or the
    surrounding asyncio task is cancelled) the helper subprocess is
    terminated and the internal tasks are awaited.

    The optional ``_spawn`` constructor argument is a test seam: when
    set, it replaces the production ``asyncio.create_subprocess_exec``
    call with a callable that returns a process-shaped object whose
    ``stdout`` is an async-iterable of bytes lines and whose ``wait``
    coroutine resolves to a return code.
    """

    def __init__(
        self,
        helper_path: str,
        *,
        ttl_s: float = 30.0,
        snapshot_interval_s: float = 1.0,
        vendors: dict[int, str] | None = None,
        ouis: dict[str, str] | None = None,
        member_uuids: dict[str, str] | None = None,
        _spawn: Callable[[], Awaitable[Any]] | None = None,
    ) -> None:
        self._helper_path = helper_path
        self._ttl_s = ttl_s
        self._snapshot_interval_s = snapshot_interval_s
        self._vendors = vendors if vendors is not None else load_vendors()
        # OUI lookup is only consulted for connected peripherals (which
        # arrive without manufacturer_data). Lazy-load on first use; the
        # bundled JSON parses in well under a millisecond.
        self._ouis = ouis if ouis is not None else load_ouis()
        # SIG-assigned member service UUIDs. Used as a vendor fallback
        # when the advertisement omits manufacturer_data, plus for
        # service-column labelling.
        self._member_uuids = (
            member_uuids if member_uuids is not None else load_member_uuids()
        )
        self._devices: dict[str, BLEDevice] = {}
        # Currently-connected peripherals from the helper's
        # retrieveConnectedPeripherals snapshot. Lives in a parallel
        # dict because (a) entries have no RSSI / UUID-rotation, (b)
        # they are pruned by the helper's "connected_snapshot" sentinel
        # rather than the advertising-side TTL, and (c) merge_for_display
        # never sees them — they have stable identities.
        self._connected: dict[str, BLEDevice] = {}
        self._queue: asyncio.Queue[BLEScanUpdate] = asyncio.Queue()
        self._proc: Any = None
        self._permission_state: str = "unknown"
        self._tasks: list[asyncio.Task[Any]] = []
        self._stopped = False
        self._spawn_override = _spawn

    async def events(self) -> AsyncIterator[BLEScanUpdate]:
        loop = asyncio.get_running_loop()
        self._tasks = [
            loop.create_task(self._reader_loop(), name="ble-reader"),
            loop.create_task(self._snapshot_loop(), name="ble-snapshot"),
        ]
        try:
            while True:
                yield await self._queue.get()
        finally:
            self.stop()
            await asyncio.gather(*self._tasks, return_exceptions=True)

    def stop(self) -> None:
        self._stopped = True
        for t in self._tasks:
            t.cancel()
        proc = self._proc
        if proc is not None and getattr(proc, "returncode", None) is None:
            try:
                proc.terminate()
            except (ProcessLookupError, OSError):
                pass

    async def _reader_loop(self) -> None:
        try:
            if self._spawn_override is not None:
                self._proc = await self._spawn_override()
            else:
                self._proc = await asyncio.create_subprocess_exec(
                    self._helper_path, "ble-scan",
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.DEVNULL,
                )
        except (OSError, FileNotFoundError):
            self._permission_state = "unavailable"
            return

        stdout = getattr(self._proc, "stdout", None)
        if stdout is None:
            return

        try:
            async for raw in stdout:
                if self._stopped:
                    break
                line = raw.decode("utf-8", errors="replace").rstrip()
                if not line:
                    continue
                state = update_from_line(
                    self._devices, line, vendors=self._vendors,
                    connected=self._connected, ouis=self._ouis,
                    member_uuids=self._member_uuids,
                )
                if state == "permission_denied":
                    self._permission_state = "denied"
                elif state == "error" and self._permission_state == "unknown":
                    self._permission_state = "error"
                elif state is None and self._permission_state in ("unknown", "error"):
                    # A successful parse implies we are getting real
                    # advertisements — flip to granted exactly once.
                    # Connected entries also count: a Mac with all BLE
                    # devices already paired (no fresh ads) would
                    # otherwise stay "unknown" forever.
                    if any(self._devices) or any(self._connected):
                        self._permission_state = "granted"
        except (asyncio.CancelledError, GeneratorExit):
            raise
        except Exception:
            # Any unexpected stream error: stop reading. The snapshot
            # loop continues yielding empty snapshots (per spec) until
            # the consumer breaks.
            pass

        try:
            rc = await self._proc.wait()
        except (asyncio.CancelledError, GeneratorExit):
            raise
        except Exception:
            rc = None
        # The Swift helper exits with documented codes that each carry
        # different meaning, so map every non-success rc to the most
        # specific permission_state the panel can render. Without this
        # the user sees "scanning…" indefinitely whenever the helper
        # actually died — silently masking Bluetooth-off, unsupported
        # hardware, and stale-installed-bundle scenarios.
        if rc == 3:
            self._permission_state = "denied"
        elif rc == 64:
            # 0.4.0-era helper bundles still in /Applications/ from
            # before this release reach the Swift `default:` case for
            # the unknown `ble-scan` subcommand and exit 64. Surface a
            # distinct "incompatible" state so the panel can suggest a
            # rebuild.
            self._permission_state = "incompatible"
        elif rc in (4, 5):
            # 4 = Bluetooth powered off, 5 = unsupported hardware.
            self._permission_state = "error"
        elif rc not in (None, 0):
            # Any other non-zero exit: assume something went wrong and
            # tell the user, rather than letting "granted" or "unknown"
            # linger while the panel is in fact stale.
            if self._permission_state in ("granted", "unknown"):
                self._permission_state = "error"

    async def _snapshot_loop(self) -> None:
        # Always emit at least one snapshot promptly so consumers see
        # the initial "(scanning…)" state without waiting a full
        # interval.
        try:
            while not self._stopped:
                now = datetime.now(timezone.utc)
                self._devices = expire_devices(
                    self._devices, now=now, ttl_s=self._ttl_s,
                )
                merged = merge_for_display(list(self._devices.values()))
                # Connected entries sort alphabetically by name (per spec
                # layout B); RSSI sort would be meaningless given they
                # have no signal reading. Stable, predictable order.
                connected = sorted(
                    self._connected.values(),
                    key=lambda d: ((d.name or "").lower(), d.identifier),
                )
                await self._queue.put(BLEScanUpdate(
                    devices=merged,
                    permission_state=self._permission_state,
                    connected=connected,
                ))
                await asyncio.sleep(self._snapshot_interval_s)
        except asyncio.CancelledError:
            raise
